name: CI/CD Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  # docker imageへpush,build
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. DockerHub ログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. ビルダーの作成
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. backend イメージをビルド & push
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
          platforms: linux/amd64,linux/arm64

      # 5. scheduler イメージをビルド & push
      - name: Build and push scheduler
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-scheduler:latest
          platforms: linux/amd64,linux/arm64

      # 6. frontend イメージをビルド & push
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
          platforms: linux/amd64,linux/arm64
